/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames;

import Controller.ControllerEmpleado;
import Controller.ControllerMetodos;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author arnol
 */
public class Empleado extends javax.swing.JPanel {
    
    /**
     * Creates new form Cliente
     */
    //DECLARACION DE OBJETOS
    SimpleDateFormat formato = new SimpleDateFormat("yyyy-mm-dd");
    ControllerEmpleado cemp = new ControllerEmpleado(this);
    public DefaultTableModel modelo = new DefaultTableModel();
    public TableRowSorter<DefaultTableModel> sorter;
    ControllerMetodos metodo = new ControllerMetodos();
    //DECLARACIÓN DE VARIABLES 
    public Empleado(){
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatos = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtTitulo = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        panelIzquierda = new javax.swing.JPanel();
        panelAnadir = new javax.swing.JPanel();
        txtAnadir = new javax.swing.JLabel();
        panelListar = new javax.swing.JPanel();
        txtAnadir1 = new javax.swing.JLabel();
        panelModificar = new javax.swing.JPanel();
        txtModificar = new javax.swing.JLabel();
        panelEliminar = new javax.swing.JPanel();
        txtEliminar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelCreate = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        panelData_add = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        dateFECNAC = new com.toedter.calendar.JDateChooser();
        boxCargo = new javax.swing.JComboBox<>();
        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JTextField();
        btnAdd = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panelRead = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnLupa = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JLabel();
        txtBuscador = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        panelUpdate = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnAdd1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        panelData_edit = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        boxCod = new javax.swing.JComboBox<>();
        txtNombre1 = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtDNI1 = new javax.swing.JTextField();
        txtCelular1 = new javax.swing.JTextField();
        dateFECNAC1 = new com.toedter.calendar.JDateChooser();
        boxCargo1 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txtBuscador1 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnActualizar1 = new javax.swing.JLabel();
        btnLupa1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        panelDelete = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        btnAdd2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        panelData_edit1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        boxCod2 = new javax.swing.JComboBox<>();
        txtNombre2 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        txtDNI2 = new javax.swing.JTextField();
        txtCelular2 = new javax.swing.JTextField();
        dateFECNAC2 = new com.toedter.calendar.JDateChooser();
        boxCargo2 = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        txtBuscador2 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        btnActualizar2 = new javax.swing.JLabel();
        btnLupa2 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();

        setMinimumSize(new java.awt.Dimension(950, 600));
        setPreferredSize(new java.awt.Dimension(950, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSuperior.setBackground(new java.awt.Color(0, 0, 0));
        panelSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        panelSuperior.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 63, 530, 10));

        txtTitulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("GESTIONAR EMPLEADOS");
        panelSuperior.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 27, 530, 30));

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/farmacia.png"))); // NOI18N
        panelSuperior.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 59, 50));

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/farmacia.png"))); // NOI18N
        panelSuperior.add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 59, 50));

        panelDatos.add(panelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 100));

        panelIzquierda.setBackground(new java.awt.Color(204, 204, 204));
        panelIzquierda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAnadir.setBackground(new java.awt.Color(255, 255, 255));
        panelAnadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelAnadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAnadirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAnadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAnadirMouseExited(evt);
            }
        });
        panelAnadir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAnadir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAnadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnadir.setText("Añadir");
        panelAnadir.add(txtAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 37));

        panelIzquierda.add(panelAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        panelListar.setBackground(new java.awt.Color(255, 255, 255));
        panelListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelListarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelListarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelListarMouseExited(evt);
            }
        });
        panelListar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAnadir1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAnadir1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnadir1.setText("Listar");
        panelListar.add(txtAnadir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 37));

        panelIzquierda.add(panelListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        panelModificar.setBackground(new java.awt.Color(255, 255, 255));
        panelModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelModificarMouseExited(evt);
            }
        });
        panelModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtModificar.setText("Modificar");
        panelModificar.add(txtModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 37));

        panelIzquierda.add(panelModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        panelEliminar.setBackground(new java.awt.Color(255, 255, 255));
        panelEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEliminarMouseExited(evt);
            }
        });
        panelEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEliminar.setText("Eliminar");
        panelEliminar.add(txtEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 37));

        panelIzquierda.add(panelEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empleado.png"))); // NOI18N
        panelIzquierda.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 140, 140));

        panelDatos.add(panelIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 190, 500));

        panelCreate.setBackground(new java.awt.Color(255, 255, 255));
        panelCreate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Registrar empleado:");
        panelCreate.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        panelCreate.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 120, 10));

        panelData_add.setBackground(new java.awt.Color(224, 224, 224));
        panelData_add.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelData_add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nombre:");
        panelData_add.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 20));

        jLabel4.setText("Apellidos:");
        panelData_add.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel5.setText("DNI:");
        panelData_add.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel6.setText("Celular:");
        panelData_add.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jLabel7.setText("Fecha de nacimiento:");
        panelData_add.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel8.setText("Cargo:");
        panelData_add.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel9.setText("Usuario:");
        panelData_add.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel10.setText("Contraseña:");
        panelData_add.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        panelData_add.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 160, -1));

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        panelData_add.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 160, -1));

        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNIKeyTyped(evt);
            }
        });
        panelData_add.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 160, -1));

        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularKeyTyped(evt);
            }
        });
        panelData_add.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 160, -1));
        panelData_add.add(dateFECNAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 100, -1));

        boxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Quimico", "Jefe de almacen" }));
        boxCargo.setSelectedIndex(-1);
        panelData_add.add(boxCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 160, -1));
        panelData_add.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 160, -1));
        panelData_add.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 160, -1));

        panelCreate.add(panelData_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 550, 260));

        btnAdd.setBackground(new java.awt.Color(153, 153, 153));
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Guardar información");
        btnAdd.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        panelCreate.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 130, 30));

        panelDatos.add(panelCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 760, 500));

        panelRead.setBackground(new java.awt.Color(255, 255, 255));
        panelRead.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Apellidos", "DNI", "Celular", "Fecha de nacimiento", "Cargo"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setMinWidth(50);
            tabla.getColumnModel().getColumn(0).setMaxWidth(50);
            tabla.getColumnModel().getColumn(1).setPreferredWidth(50);
            tabla.getColumnModel().getColumn(3).setPreferredWidth(50);
            tabla.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        panelRead.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 56, 626, 407));

        btnLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupita.png"))); // NOI18N
        btnLupa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRead.add(btnLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 40, 30));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRead.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 30));

        txtBuscador.setBorder(null);
        txtBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscadorMouseClicked(evt);
            }
        });
        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyTyped(evt);
            }
        });
        panelRead.add(txtBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 520, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        panelRead.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 520, 20));

        panelDatos.add(panelRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 760, 500));

        panelUpdate.setBackground(new java.awt.Color(255, 255, 255));
        panelUpdate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel12.setText("Modificar empleados");
        panelUpdate.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        panelUpdate.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 120, 10));

        btnAdd1.setBackground(new java.awt.Color(153, 153, 153));
        btnAdd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd1MouseClicked(evt);
            }
        });
        btnAdd1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Guardar información");
        btnAdd1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        panelUpdate.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 130, 30));

        panelData_edit.setBackground(new java.awt.Color(224, 224, 224));
        panelData_edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelData_edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Nombre:");
        panelData_edit.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, 20));

        jLabel15.setText("Apellidos:");
        panelData_edit.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLabel16.setText("DNI:");
        panelData_edit.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel17.setText("Celular:");
        panelData_edit.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel18.setText("Fecha de nacimiento:");
        panelData_edit.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel19.setText("Cargo:");
        panelData_edit.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        panelData_edit.add(boxCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 100, -1));

        txtNombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre1KeyTyped(evt);
            }
        });
        panelData_edit.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 160, -1));

        txtApellido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellido1KeyTyped(evt);
            }
        });
        panelData_edit.add(txtApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 160, -1));

        txtDNI1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNI1KeyTyped(evt);
            }
        });
        panelData_edit.add(txtDNI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 160, -1));

        txtCelular1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelular1KeyTyped(evt);
            }
        });
        panelData_edit.add(txtCelular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 160, -1));
        panelData_edit.add(dateFECNAC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 100, -1));

        boxCargo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Quimico", "Jefe de almacen" }));
        boxCargo1.setSelectedIndex(-1);
        panelData_edit.add(boxCargo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 160, -1));

        jLabel20.setText("Código de empleado:");
        panelData_edit.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtBuscador1.setBorder(null);
        txtBuscador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscador1MouseClicked(evt);
            }
        });
        txtBuscador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscador1KeyTyped(evt);
            }
        });
        panelData_edit.add(txtBuscador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 160, 20));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        panelData_edit.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 160, 20));

        btnActualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btnActualizar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelData_edit.add(btnActualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 40, 40));

        btnLupa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupita.png"))); // NOI18N
        btnLupa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelData_edit.add(btnLupa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 40, 40));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        panelData_edit.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 550, 10));

        panelUpdate.add(panelData_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 550, 260));

        panelDatos.add(panelUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 760, 500));

        panelDelete.setBackground(new java.awt.Color(255, 255, 255));
        panelDelete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel21.setText("Eliminar empleados");
        panelDelete.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        panelDelete.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 120, 10));

        btnAdd2.setBackground(new java.awt.Color(153, 153, 153));
        btnAdd2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd2MouseClicked(evt);
            }
        });
        btnAdd2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Eliminar empleado");
        btnAdd2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        panelDelete.add(btnAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 130, 30));

        panelData_edit1.setBackground(new java.awt.Color(224, 224, 224));
        panelData_edit1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelData_edit1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setText("Nombre:");
        panelData_edit1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, 20));

        jLabel24.setText("Apellidos:");
        panelData_edit1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLabel25.setText("DNI:");
        panelData_edit1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel26.setText("Celular:");
        panelData_edit1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel27.setText("Fecha de nacimiento:");
        panelData_edit1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel28.setText("Cargo:");
        panelData_edit1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        panelData_edit1.add(boxCod2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 100, -1));

        txtNombre2.setEditable(false);
        txtNombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre2KeyTyped(evt);
            }
        });
        panelData_edit1.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 160, -1));

        txtApellido2.setEditable(false);
        txtApellido2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellido2KeyTyped(evt);
            }
        });
        panelData_edit1.add(txtApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 160, -1));

        txtDNI2.setEditable(false);
        txtDNI2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNI2KeyTyped(evt);
            }
        });
        panelData_edit1.add(txtDNI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 160, -1));

        txtCelular2.setEditable(false);
        txtCelular2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelular2KeyTyped(evt);
            }
        });
        panelData_edit1.add(txtCelular2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 160, -1));

        dateFECNAC2.setEnabled(false);
        panelData_edit1.add(dateFECNAC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 100, -1));

        boxCargo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Quimico", "Jefe de almacen" }));
        boxCargo2.setSelectedIndex(-1);
        boxCargo2.setEnabled(false);
        panelData_edit1.add(boxCargo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 160, -1));

        jLabel29.setText("Código de empleado:");
        panelData_edit1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtBuscador2.setBorder(null);
        txtBuscador2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscador2MouseClicked(evt);
            }
        });
        txtBuscador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscador2KeyTyped(evt);
            }
        });
        panelData_edit1.add(txtBuscador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 160, 20));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        panelData_edit1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 160, 20));

        btnActualizar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btnActualizar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelData_edit1.add(btnActualizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 40, 40));

        btnLupa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupita.png"))); // NOI18N
        btnLupa2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelData_edit1.add(btnLupa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 40, 40));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        panelData_edit1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 550, 10));

        panelDelete.add(panelData_edit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 550, 260));

        panelDatos.add(panelDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 760, 500));

        add(panelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        
    }//GEN-LAST:event_tablaMouseClicked

    private void panelAnadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnadirMouseClicked
        cemp.visible_create();
        //SE CAMBIA EL TITULO
        txtTitulo.setText("AÑADIR EMPLEADOS");
        //SE LIMPIAN LOS COMPOS
        cemp.limpiar_campos();
    }//GEN-LAST:event_panelAnadirMouseClicked

    private void panelAnadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnadirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAnadirMouseEntered

    private void panelAnadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnadirMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAnadirMouseExited

    private void panelModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelModificarMouseClicked
        cemp.visible_update();
        //SE CAMBIA EL TITULO
        txtTitulo.setText("MODIFICAR EMPLEADOS");
        //SE LIMPIAN LOS COMBOBOXES
        cemp.limpiar_combobox();
        //llenar comboboxes
        cemp.listar_combobox();
        //SE LIMPIAN LOS CAMPOS
        cemp.limpiar_campos();
        //SE BLOQUEAN LOS CAMPOS
        cemp.bloquear_camposUpdate();
    }//GEN-LAST:event_panelModificarMouseClicked

    private void panelModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelModificarMouseEntered

    }//GEN-LAST:event_panelModificarMouseEntered

    private void panelModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelModificarMouseExited

    }//GEN-LAST:event_panelModificarMouseExited

    private void panelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEliminarMouseClicked
        cemp.visible_delete();
        //SE CAMBIA EL TITULO
        txtTitulo.setText("ELIMINAR EMPLEADOS");
        //SE LIMPIAN LOS COMBOBOXES
        cemp.limpiar_combobox();
        //llenar comboboxes
        cemp.listar_combobox2();
        //SE LIMPIAN LOS CAMPOS
        cemp.limpiar_campos();
    }//GEN-LAST:event_panelEliminarMouseClicked

    private void panelEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEliminarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEliminarMouseEntered

    private void panelEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEliminarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEliminarMouseExited

    private void panelListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelListarMouseClicked
        cemp.visible_read();
        //SE CAMBIA EL TITULO
        txtTitulo.setText("VISTA DE EMPLEADOS");
        //LISTA USUARIOS
        cemp.limpiar_campos();
        cemp.limpiarTabla();
        cemp.listar();
    }//GEN-LAST:event_panelListarMouseClicked

    private void panelListarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelListarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelListarMouseEntered

    private void panelListarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelListarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelListarMouseExited

    private void txtBuscadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorMouseClicked
        if(this.txtBuscador.getText().equals("Ingrese nombre del empleado")){
            this.txtBuscador.setText("");
            this.txtBuscador.setForeground(Color.BLACK);
            this.txtBuscador.getCaret().setVisible(true);
        }
    }//GEN-LAST:event_txtBuscadorMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        if(this.txtNombre.getText().equals("")||this.txtApellido.getText().equals("")||
                this.txtDNI.getText().equals("")||this.txtCelular.getText().equals("")||
                this.txtUsuario.getText().equals("")||this.txtContrasena.getText().equals("")||
                this.dateFECNAC.getDate().toString().equals("")||this.boxCargo.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }else{
            cemp.agregar();
            cemp.limpiarTabla();
            cemp.limpiar_campos();
            cemp.listar();
            //SE HACE VISIBLE EL READ
            cemp.visible_read();
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char validar = evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
        if(this.txtDNI.getText().length()>=8){
            evt.consume();
        }
    }//GEN-LAST:event_txtDNIKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
        if(this.txtCelular.getText().length()>=9){
            evt.consume();
        }
    }//GEN-LAST:event_txtCelularKeyTyped

    private void btnAdd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd1MouseClicked
        if(this.txtNombre1.getText().equals("")||this.txtApellido1.getText().equals("")||
                this.txtDNI1.getText().equals("")||this.txtCelular1.getText().equals("")||
                this.dateFECNAC1.getDate().toString().equals("")||this.boxCargo1.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }else{
            //SE EDITA
            cemp.actualizar();
            //SE LIMPIAN LOS DATOS
            cemp.limpiar_campos();
            //REDIRIGIR A READ
            cemp.visible_read();
            //limpiar
            cemp.limpiar_campos();
            cemp.limpiarTabla();
            //listar
            cemp.listar();
        }
    }//GEN-LAST:event_btnAdd1MouseClicked

    private void txtNombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre1KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtNombre1KeyTyped

    private void txtApellido1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido1KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtApellido1KeyTyped

    private void txtDNI1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNI1KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
        if(this.txtDNI1.getText().length()>=8){
            evt.consume();
        }
    }//GEN-LAST:event_txtDNI1KeyTyped

    private void txtCelular1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelular1KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
        if(this.txtCelular1.getText().length()>=9){
            evt.consume();
        }
    }//GEN-LAST:event_txtCelular1KeyTyped

    private void txtBuscador1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscador1MouseClicked
        if(this.txtBuscador1.getText().equals("Ingrese código del empleado")){
            this.txtBuscador1.setText("");
            this.txtBuscador1.setForeground(Color.BLACK);
            this.txtBuscador1.getCaret().setVisible(true);
        }
    }//GEN-LAST:event_txtBuscador1MouseClicked

    private void txtBuscador1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscador1KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
        if(this.txtBuscador1.getText().length()>=9){
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscador1KeyTyped

    private void txtBuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtBuscadorKeyTyped

    private void btnAdd2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd2MouseClicked
        //SE ELIMINA
        boolean bandera_delete=cemp.eliminar();
        if(bandera_delete){
            //SE LIMPIAN LOS DATOS
            cemp.limpiar_campos();
            //REDIRIGIR A READ
            cemp.visible_read();
            //limpiar
            cemp.limpiar_campos();
            cemp.limpiarTabla();
            //listar
            cemp.listar();
        }
    }//GEN-LAST:event_btnAdd2MouseClicked

    private void txtNombre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre2KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtNombre2KeyTyped

    private void txtApellido2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido2KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtApellido2KeyTyped

    private void txtDNI2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNI2KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
        if(this.txtDNI2.getText().length()>=8){
            evt.consume();
        }
    }//GEN-LAST:event_txtDNI2KeyTyped

    private void txtCelular2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelular2KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
        if(this.txtCelular2.getText().length()>=9){
            evt.consume();
        }
    }//GEN-LAST:event_txtCelular2KeyTyped

    private void txtBuscador2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscador2MouseClicked
        if(this.txtBuscador2.getText().equals("Ingrese código del empleado")){
            this.txtBuscador2.setText("");
            this.txtBuscador2.setForeground(Color.BLACK);
            this.txtBuscador2.getCaret().setVisible(true);
        }
    }//GEN-LAST:event_txtBuscador2MouseClicked

    private void txtBuscador2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscador2KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
        if(this.txtBuscador2.getText().length()>=9){
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscador2KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boxCargo;
    public javax.swing.JComboBox<String> boxCargo1;
    public javax.swing.JComboBox<String> boxCargo2;
    public javax.swing.JComboBox<String> boxCod;
    public javax.swing.JComboBox<String> boxCod2;
    public javax.swing.JLabel btnActualizar;
    public javax.swing.JLabel btnActualizar1;
    public javax.swing.JLabel btnActualizar2;
    private javax.swing.JPanel btnAdd;
    private javax.swing.JPanel btnAdd1;
    private javax.swing.JPanel btnAdd2;
    public javax.swing.JLabel btnLupa;
    public javax.swing.JLabel btnLupa1;
    public javax.swing.JLabel btnLupa2;
    public com.toedter.calendar.JDateChooser dateFECNAC;
    public com.toedter.calendar.JDateChooser dateFECNAC1;
    public com.toedter.calendar.JDateChooser dateFECNAC2;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JPanel panelAnadir;
    public javax.swing.JPanel panelCreate;
    private javax.swing.JPanel panelData_add;
    private javax.swing.JPanel panelData_edit;
    private javax.swing.JPanel panelData_edit1;
    public javax.swing.JPanel panelDatos;
    public javax.swing.JPanel panelDelete;
    public javax.swing.JPanel panelEliminar;
    private javax.swing.JPanel panelIzquierda;
    public javax.swing.JPanel panelListar;
    public javax.swing.JPanel panelModificar;
    public javax.swing.JPanel panelRead;
    private javax.swing.JPanel panelSuperior;
    public javax.swing.JPanel panelUpdate;
    public javax.swing.JTable tabla;
    private javax.swing.JLabel txtAnadir;
    private javax.swing.JLabel txtAnadir1;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtApellido1;
    public javax.swing.JTextField txtApellido2;
    public javax.swing.JTextField txtBuscador;
    public javax.swing.JTextField txtBuscador1;
    public javax.swing.JTextField txtBuscador2;
    public javax.swing.JTextField txtCelular;
    public javax.swing.JTextField txtCelular1;
    public javax.swing.JTextField txtCelular2;
    public javax.swing.JTextField txtContrasena;
    public javax.swing.JTextField txtDNI;
    public javax.swing.JTextField txtDNI1;
    public javax.swing.JTextField txtDNI2;
    private javax.swing.JLabel txtEliminar;
    private javax.swing.JLabel txtModificar;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNombre1;
    public javax.swing.JTextField txtNombre2;
    private javax.swing.JLabel txtTitulo;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
