/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;


import Controller.ControllerPedido;
import Controller.ControllerRealizarPago;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author arnold
 */
public class Pedido extends javax.swing.JPanel {
    //Declaración de objetos
    ControllerPedido cped = new ControllerPedido(this);
    
    //ATRIBUTOS NECESARIOS
    Boolean estadoLabels=false;
    public DefaultTableModel modelo = new DefaultTableModel();
    public TableRowSorter<DefaultTableModel> sorter;
    public int CODCIA;//Variable global
    int xMouse,yMouse;
    //Constructor
    public Pedido() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBtnEliminar = new javax.swing.ButtonGroup();
        grupoBtnOrdenar = new javax.swing.ButtonGroup();
        panelDatos = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtTitulo = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        panelIzquierda = new javax.swing.JPanel();
        panelAnadir = new javax.swing.JPanel();
        txtAnadir = new javax.swing.JLabel();
        panelListar = new javax.swing.JPanel();
        txtAnadir1 = new javax.swing.JLabel();
        panelModificar = new javax.swing.JPanel();
        txtModificar = new javax.swing.JLabel();
        panelEliminar = new javax.swing.JPanel();
        txtEliminar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelUpdate = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnAdd1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        panelData_edit = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        boxCodprod3 = new javax.swing.JComboBox<>();
        txtNombre3 = new javax.swing.JTextField();
        txtDescripcion3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtBuscador3 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnActualizar3 = new javax.swing.JLabel();
        btnLupa3 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        boxCodprov3 = new javax.swing.JComboBox<>();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad3 = new javax.swing.JTextField();
        eliminarproducto = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelCreate = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnAdd = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panelData_add = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        boxCodprod1 = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtBuscador1 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        btnActualizar1 = new javax.swing.JLabel();
        btnLupa1 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        txtCantidad1 = new javax.swing.JTextField();
        boxCodprov1 = new javax.swing.JComboBox<>();
        panelRead = new javax.swing.JPanel();
        panelRealizarPago = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnLupa2 = new javax.swing.JLabel();
        btnActualizar2 = new javax.swing.JLabel();
        txtBuscador2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSuperior.setBackground(new java.awt.Color(0, 0, 0));
        panelSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        panelSuperior.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 63, 530, 10));

        txtTitulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("GESTIONAR PEDIDO");
        panelSuperior.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 27, 530, 30));

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/farmacia.png"))); // NOI18N
        panelSuperior.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 59, 50));

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/farmacia.png"))); // NOI18N
        panelSuperior.add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 59, 50));

        panelDatos.add(panelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 100));

        panelIzquierda.setBackground(new java.awt.Color(204, 204, 204));
        panelIzquierda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAnadir.setBackground(new java.awt.Color(255, 255, 255));
        panelAnadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelAnadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAnadirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAnadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAnadirMouseExited(evt);
            }
        });
        panelAnadir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAnadir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAnadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnadir.setText("Añadir");
        panelAnadir.add(txtAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 37));

        panelIzquierda.add(panelAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        panelListar.setBackground(new java.awt.Color(255, 255, 255));
        panelListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelListarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelListarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelListarMouseExited(evt);
            }
        });
        panelListar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAnadir1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAnadir1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnadir1.setText("Listar");
        panelListar.add(txtAnadir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 37));

        panelIzquierda.add(panelListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        panelModificar.setBackground(new java.awt.Color(255, 255, 255));
        panelModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelModificarMouseExited(evt);
            }
        });
        panelModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtModificar.setText("Modificar");
        panelModificar.add(txtModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 37));

        panelIzquierda.add(panelModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        panelEliminar.setBackground(new java.awt.Color(255, 255, 255));
        panelEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEliminarMouseExited(evt);
            }
        });
        panelEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEliminar.setText("Eliminar");
        panelEliminar.add(txtEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 37));

        panelIzquierda.add(panelEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgPedido.png"))); // NOI18N
        panelIzquierda.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 140, 140));

        panelDatos.add(panelIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 190, 500));

        panelUpdate.setBackground(new java.awt.Color(255, 255, 255));
        panelUpdate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel12.setText("Modificar pedido:");
        panelUpdate.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        panelUpdate.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 100, 10));

        btnAdd1.setBackground(new java.awt.Color(153, 153, 153));
        btnAdd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd1MouseClicked(evt);
            }
        });
        btnAdd1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Guardar información");
        btnAdd1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        panelUpdate.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 130, 30));

        panelData_edit.setBackground(new java.awt.Color(224, 224, 224));
        panelData_edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelData_edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Nombre:");
        panelData_edit.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, 20));

        jLabel16.setText("Descripcion:");
        panelData_edit.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel18.setText("Proveedor:");
        panelData_edit.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 166, -1, 30));

        panelData_edit.add(boxCodprod3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 100, -1));

        txtNombre3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre3KeyTyped(evt);
            }
        });
        panelData_edit.add(txtNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 410, -1));

        txtDescripcion3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcion3KeyTyped(evt);
            }
        });
        panelData_edit.add(txtDescripcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 410, -1));

        jLabel20.setText("Código de producto:");
        panelData_edit.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtBuscador3.setBorder(null);
        txtBuscador3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscador3MouseClicked(evt);
            }
        });
        txtBuscador3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscador3KeyTyped(evt);
            }
        });
        panelData_edit.add(txtBuscador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 160, 20));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        panelData_edit.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 160, 20));

        btnActualizar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btnActualizar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelData_edit.add(btnActualizar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 40, 40));

        btnLupa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupita.png"))); // NOI18N
        btnLupa3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelData_edit.add(btnLupa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 40, 40));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        panelData_edit.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 550, 10));

        panelData_edit.add(boxCodprov3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 130, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        panelData_edit.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 550, 10));

        jLabel3.setText("Cantidad:");
        panelData_edit.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        txtCantidad3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidad3KeyTyped(evt);
            }
        });
        panelData_edit.add(txtCantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 130, -1));

        eliminarproducto.setBackground(new java.awt.Color(224, 224, 224));
        eliminarproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarproducto.setDoubleBuffered(false);
        eliminarproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarproductoMouseClicked(evt);
            }
        });
        eliminarproducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminarPNG.jpg"))); // NOI18N
        eliminarproducto.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        panelData_edit.add(eliminarproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 40, 40));

        panelUpdate.add(panelData_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 550, 260));

        panelDatos.add(panelUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 760, 500));

        panelCreate.setBackground(new java.awt.Color(255, 255, 255));
        panelCreate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Añadir producto:");
        panelCreate.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        panelCreate.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 100, 10));

        btnAdd.setBackground(new java.awt.Color(153, 153, 153));
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
        });
        btnAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Guardar información");
        btnAdd.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        panelCreate.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 130, 30));

        panelData_add.setBackground(new java.awt.Color(224, 224, 224));
        panelData_add.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelData_add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setText("Nombre:");
        panelData_add.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, 20));

        jLabel25.setText("Descripción:");
        panelData_add.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel27.setText("Cantidad:");
        panelData_add.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 20));

        panelData_add.add(boxCodprod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 100, -1));

        txtNombre.setEditable(false);
        panelData_add.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 410, -1));

        txtDescripcion.setEditable(false);
        panelData_add.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 410, -1));

        jLabel29.setText("Código de producto:");
        panelData_add.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtBuscador1.setBorder(null);
        txtBuscador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscador1MouseClicked(evt);
            }
        });
        panelData_add.add(txtBuscador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 160, 20));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        panelData_add.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 160, 20));

        btnActualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btnActualizar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelData_add.add(btnActualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 40, 40));

        btnLupa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupita.png"))); // NOI18N
        btnLupa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelData_add.add(btnLupa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 40, 40));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        panelData_add.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 550, 10));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        panelData_add.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 550, 10));

        jLabel28.setText("Proveedor:");
        panelData_add.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtCantidad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidad1KeyTyped(evt);
            }
        });
        panelData_add.add(txtCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 410, -1));

        boxCodprov1.setEnabled(false);
        panelData_add.add(boxCodprov1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 120, -1));

        panelCreate.add(panelData_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 550, 260));

        panelDatos.add(panelCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 760, 500));

        panelRead.setBackground(new java.awt.Color(255, 255, 255));
        panelRead.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRealizarPago.setBackground(new java.awt.Color(0, 0, 0));
        panelRealizarPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRealizarPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRealizarPagoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRealizarPagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRealizarPagoMouseExited(evt);
            }
        });
        panelRealizarPago.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Realizar pago");
        panelRealizarPago.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        panelRead.add(panelRealizarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 110, 30));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Descripción", "Proveedor", "Cantidad"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        panelRead.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 56, 626, 360));

        btnLupa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupita.png"))); // NOI18N
        btnLupa2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRead.add(btnLupa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 40, 30));

        btnActualizar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btnActualizar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRead.add(btnActualizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 30));

        txtBuscador2.setBorder(null);
        txtBuscador2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscador2MouseClicked(evt);
            }
        });
        txtBuscador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscador2KeyTyped(evt);
            }
        });
        panelRead.add(txtBuscador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 520, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        panelRead.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 520, 20));

        panelDatos.add(panelRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 760, 500));

        add(panelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        
    }//GEN-LAST:event_formMousePressed

    private void panelAnadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnadirMouseClicked
        cped.visible_create();
        //SE CAMBIA EL TITULO
        txtTitulo.setText("AÑADIR PRODUCTOS");
        //SE LIMPIAN LOS COMBOBOXES
        cped.limpiar_combobox();
        //llenar comboboxes
        cped.listar_combobox1();
        //SE LIMPIAN LOS CAMPOS
        cped.limpiar_campos();
    }//GEN-LAST:event_panelAnadirMouseClicked

    private void panelAnadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnadirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAnadirMouseEntered

    private void panelAnadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnadirMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAnadirMouseExited

    private void panelListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelListarMouseClicked
        cped.visible_read();
        //SE CAMBIA EL TITULO
        txtTitulo.setText("VISTA DEL PEDIDO");
        //LISTA USUARIOS
        cped.limpiar_campos();
        cped.limpiarTabla();
        cped.listar();
    }//GEN-LAST:event_panelListarMouseClicked

    private void panelListarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelListarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelListarMouseEntered

    private void panelListarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelListarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelListarMouseExited

    private void panelModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelModificarMouseClicked
        cped.visible_update();
        //SE CAMBIA EL TITULO
        txtTitulo.setText("MODIFICAR PEDIDO");
        //SE LIMPIAN LOS COMBOBOXES
        cped.limpiar_combobox();
        //llenar comboboxes
        cped.listar_combobox3();
        //SE LIMPIAN LOS CAMPOS
        cped.limpiar_campos();
        //SE BLOQUEAN LOS CAMPOS
        cped.bloquear_camposUpdate();
    }//GEN-LAST:event_panelModificarMouseClicked

    private void panelModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelModificarMouseEntered

    }//GEN-LAST:event_panelModificarMouseEntered

    private void panelModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelModificarMouseExited

    }//GEN-LAST:event_panelModificarMouseExited

    private void panelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEliminarMouseClicked
        //SE CAMBIA EL TITULO
        txtTitulo.setText("ELIMINAR PEDIDO");
        //SE ELIMINA LA LISTA
        boolean bandera=cped.eliminar();
        if(bandera){
            JOptionPane.showMessageDialog(null, "Pedido eliminado con éxito!!");
            //SE LIMPIAN LOS COMBOBOXES
            cped.limpiar_combobox();
            //SE LIMPIAN LOS CAMPOS
            cped.limpiar_campos();
            cped.limpiarTabla();
            cped.listar();
            cped.visible_read();
        }
    }//GEN-LAST:event_panelEliminarMouseClicked

    private void panelEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEliminarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEliminarMouseEntered

    private void panelEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEliminarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEliminarMouseExited

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        if(this.txtNombre.getText().equals("")||this.txtDescripcion.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }else{
            if(cped.verificarStock(boxCodprod1.getSelectedItem().toString(),this.txtCantidad1.getText())){
                cped.agregar();
                cped.limpiarTabla();
                cped.limpiar_campos();
                cped.listar();
                //SE HACE VISIBLE EL READ
                cped.visible_read();
            }else{
                JOptionPane.showMessageDialog(null, "No hay stock disponible!");
            }
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked

    }//GEN-LAST:event_tablaMouseClicked

    private void txtBuscador2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscador2MouseClicked
        if(this.txtBuscador2.getText().equals("Ingrese nombre del producto")){
            this.txtBuscador2.setText("");
            this.txtBuscador2.setForeground(Color.BLACK);
            this.txtBuscador2.getCaret().setVisible(true);
        }
    }//GEN-LAST:event_txtBuscador2MouseClicked

    private void txtBuscador2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscador2KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtBuscador2KeyTyped

    private void btnAdd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd1MouseClicked
        if(this.txtNombre3.getText().equals("")||this.txtDescripcion3.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }else{
            if(cped.verificarStock(boxCodprod3.getSelectedItem().toString(),this.txtCantidad3.getText())){
                //SE EDITA
                cped.actualizar();
                //SE LIMPIAN LOS DATOS
                cped.limpiar_campos();
                //REDIRIGIR A READ
                cped.visible_read();
                //limpiar
                cped.limpiar_campos();
                cped.limpiarTabla();
                //listar
                cped.listar();
            }else{
                JOptionPane.showMessageDialog(null, "No hay stock disponible!");
            }
        }
    }//GEN-LAST:event_btnAdd1MouseClicked

    private void txtNombre3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre3KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtNombre3KeyTyped

    private void txtDescripcion3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcion3KeyTyped

    }//GEN-LAST:event_txtDescripcion3KeyTyped

    private void txtBuscador3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscador3MouseClicked
        if(this.txtBuscador3.getText().equals("Ingrese código del producto")){
            this.txtBuscador3.setText("");
            this.txtBuscador3.setForeground(Color.BLACK);
            this.txtBuscador3.getCaret().setVisible(true);
        }
    }//GEN-LAST:event_txtBuscador3MouseClicked

    private void txtBuscador3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscador3KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
        if(this.txtBuscador3.getText().length()>=9){
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscador3KeyTyped

    private void txtBuscador1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscador1MouseClicked
        if(this.txtBuscador1.getText().equals("Ingrese código del producto")){
            this.txtBuscador1.setText("");
            this.txtBuscador1.setForeground(Color.BLACK);
            this.txtBuscador1.getCaret().setVisible(true);
        }
    }//GEN-LAST:event_txtBuscador1MouseClicked

    private void txtCantidad3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad3KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
        if(this.txtCantidad3.getText().length()>=9){
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidad3KeyTyped

    private void eliminarproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarproductoMouseClicked
        boolean bandera=cped.eliminar_producto();
        if(bandera){
            JOptionPane.showMessageDialog(null, "Producto eliminado con éxito!!");
            //SE LIMPIAN LOS COMBOBOXES
            cped.limpiar_combobox();
            //SE LIMPIAN LOS CAMPOS
            cped.limpiar_campos();
            cped.limpiarTabla();
            cped.listar();
            cped.visible_read();
        }
    }//GEN-LAST:event_eliminarproductoMouseClicked

    private void txtCantidad1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad1KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
        if(this.txtCantidad1.getText().length()>=9){
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidad1KeyTyped

    private void panelRealizarPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRealizarPagoMouseClicked
        ControllerRealizarPago controller = new ControllerRealizarPago(cped);
        if(!ControllerRealizarPago.pagar){
            controller.run();
            ControllerRealizarPago.pagar=true;
        }
    }//GEN-LAST:event_panelRealizarPagoMouseClicked

    private void panelRealizarPagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRealizarPagoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelRealizarPagoMouseEntered

    private void panelRealizarPagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRealizarPagoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelRealizarPagoMouseExited

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMouseEntered
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boxCodprod1;
    public javax.swing.JComboBox<String> boxCodprod3;
    public javax.swing.JComboBox<String> boxCodprov1;
    public javax.swing.JComboBox<String> boxCodprov3;
    public javax.swing.JLabel btnActualizar1;
    public javax.swing.JLabel btnActualizar2;
    public javax.swing.JLabel btnActualizar3;
    private javax.swing.JPanel btnAdd;
    private javax.swing.JPanel btnAdd1;
    public javax.swing.JLabel btnLupa1;
    public javax.swing.JLabel btnLupa2;
    public javax.swing.JLabel btnLupa3;
    public javax.swing.JPanel eliminarproducto;
    public javax.swing.ButtonGroup grupoBtnEliminar;
    public javax.swing.ButtonGroup grupoBtnOrdenar;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JPanel panelAnadir;
    public javax.swing.JPanel panelCreate;
    private javax.swing.JPanel panelData_add;
    private javax.swing.JPanel panelData_edit;
    public javax.swing.JPanel panelDatos;
    public javax.swing.JPanel panelEliminar;
    private javax.swing.JPanel panelIzquierda;
    public javax.swing.JPanel panelListar;
    public javax.swing.JPanel panelModificar;
    public javax.swing.JPanel panelRead;
    public javax.swing.JPanel panelRealizarPago;
    private javax.swing.JPanel panelSuperior;
    public javax.swing.JPanel panelUpdate;
    public javax.swing.JTable tabla;
    private javax.swing.JLabel txtAnadir;
    private javax.swing.JLabel txtAnadir1;
    public javax.swing.JTextField txtBuscador1;
    public javax.swing.JTextField txtBuscador2;
    public javax.swing.JTextField txtBuscador3;
    public javax.swing.JTextField txtCantidad1;
    public javax.swing.JTextField txtCantidad3;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtDescripcion3;
    private javax.swing.JLabel txtEliminar;
    private javax.swing.JLabel txtModificar;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNombre3;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
