/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames;

import Controller.ControllerLista_Producto;
import Controller.ControllerProducto;
import Controller.ControllerMetodos;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author arnol
 */
public class Producto extends javax.swing.JPanel {
    
    /**
     * Creates new form Cliente
     */
    //DECLARACION DE OBJETOS
    ControllerProducto cprod = new ControllerProducto(this);
    ControllerLista_Producto clist_prod = new ControllerLista_Producto(this);
    int opcion=1;
    public DefaultTableModel modelo = new DefaultTableModel();
    public TableRowSorter<DefaultTableModel> sorter;
    ControllerMetodos metodo = new ControllerMetodos();
    //DECLARACIÓN DE VARIABLES 
    public Producto() {
        initComponents();
        this.panelDerecha2.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatos = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtTitulo = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        panelIzquierda = new javax.swing.JPanel();
        panelAnadir = new javax.swing.JPanel();
        txtAnadir = new javax.swing.JLabel();
        panelListar = new javax.swing.JPanel();
        txtAnadir1 = new javax.swing.JLabel();
        panelModificar = new javax.swing.JPanel();
        txtModificar = new javax.swing.JLabel();
        panelEliminar = new javax.swing.JPanel();
        txtEliminar = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        casilla1 = new javax.swing.JLabel();
        casilla2 = new javax.swing.JLabel();
        selector1 = new javax.swing.JLabel();
        selector2 = new javax.swing.JLabel();
        panelDerecha1 = new javax.swing.JPanel();
        panelCreate = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        panelData_add = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panelRead = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnLupa = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JLabel();
        txtBuscador = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        panelUpdate = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnAdd1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        panelData_edit = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        boxCod = new javax.swing.JComboBox<>();
        txtNombre1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtBuscador1 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnActualizar1 = new javax.swing.JLabel();
        btnLupa1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescripcion1 = new javax.swing.JTextArea();
        panelDelete = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        btnAdd2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        panelData_edit1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        boxCod2 = new javax.swing.JComboBox<>();
        txtNombre2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtBuscador2 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        btnActualizar2 = new javax.swing.JLabel();
        btnLupa2 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcion2 = new javax.swing.JTextArea();
        panelDerecha2 = new javax.swing.JPanel();
        panelCreate1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        panelData_add1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDist10 = new javax.swing.JComboBox<>();
        txtCodprod10 = new javax.swing.JComboBox<>();
        txtFecvenc10 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtCantidad10 = new javax.swing.JTextField();
        btnAdd10 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        panelRead1 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabla11 = new javax.swing.JTable();
        btnLupa11 = new javax.swing.JLabel();
        btnActualizar11 = new javax.swing.JLabel();
        txtBuscador11 = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        panelUpdate1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        btnAdd12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        panelData_edit2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        boxCod12 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        txtBuscador12 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        btnActualizar12 = new javax.swing.JLabel();
        btnLupa12 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        txtDist12 = new javax.swing.JComboBox<>();
        txtCodproducto12 = new javax.swing.JComboBox<>();
        txtFecvenc12 = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        txtCantidad12 = new javax.swing.JTextField();
        panelDelete1 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        btnAdd13 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        panelData_edit3 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        boxCod13 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        txtBuscador13 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        btnActualizar13 = new javax.swing.JLabel();
        btnLupa13 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        txtDist13 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        txtFecvenc13 = new com.toedter.calendar.JDateChooser();
        txtCodproducto13 = new javax.swing.JComboBox<>();
        txtCantidad13 = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(950, 600));
        setPreferredSize(new java.awt.Dimension(950, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSuperior.setBackground(new java.awt.Color(0, 0, 0));
        panelSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        panelSuperior.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 63, 530, 10));

        txtTitulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("GESTIONAR PRODUCTOS");
        panelSuperior.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 27, 530, 30));

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/farmacia.png"))); // NOI18N
        panelSuperior.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 59, 50));

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/farmacia.png"))); // NOI18N
        panelSuperior.add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 59, 50));

        panelDatos.add(panelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 100));

        panelIzquierda.setBackground(new java.awt.Color(204, 204, 204));
        panelIzquierda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAnadir.setBackground(new java.awt.Color(255, 255, 255));
        panelAnadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelAnadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAnadirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAnadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAnadirMouseExited(evt);
            }
        });
        panelAnadir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAnadir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAnadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnadir.setText("Añadir");
        panelAnadir.add(txtAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 37));

        panelIzquierda.add(panelAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        panelListar.setBackground(new java.awt.Color(255, 255, 255));
        panelListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelListarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelListarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelListarMouseExited(evt);
            }
        });
        panelListar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAnadir1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAnadir1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnadir1.setText("Listar");
        panelListar.add(txtAnadir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 37));

        panelIzquierda.add(panelListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        panelModificar.setBackground(new java.awt.Color(255, 255, 255));
        panelModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelModificarMouseExited(evt);
            }
        });
        panelModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtModificar.setText("Modificar");
        panelModificar.add(txtModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 37));

        panelIzquierda.add(panelModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        panelEliminar.setBackground(new java.awt.Color(255, 255, 255));
        panelEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEliminarMouseExited(evt);
            }
        });
        panelEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEliminar.setText("Eliminar");
        panelEliminar.add(txtEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 37));

        panelIzquierda.add(panelEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgProducto.png"))); // NOI18N
        panelIzquierda.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 140, 140));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel4.setText("Productos");
        panelIzquierda.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel7.setText("Actualizar stock");
        panelIzquierda.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, 20));

        casilla1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgCasilla.png"))); // NOI18N
        casilla1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        casilla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla1MouseClicked(evt);
            }
        });
        panelIzquierda.add(casilla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 20, 20));

        casilla2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgCasilla.png"))); // NOI18N
        casilla2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        casilla2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla2MouseClicked(evt);
            }
        });
        panelIzquierda.add(casilla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 20, 20));

        selector1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgSeleccion.png"))); // NOI18N
        panelIzquierda.add(selector1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 20, 20));

        selector2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelIzquierda.add(selector2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 20, 20));

        panelDatos.add(panelIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 190, 500));

        panelDerecha1.setBackground(new java.awt.Color(255, 255, 255));
        panelDerecha1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCreate.setBackground(new java.awt.Color(255, 255, 255));
        panelCreate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Registrar producto:");
        panelCreate.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        panelCreate.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 110, 10));

        panelData_add.setBackground(new java.awt.Color(224, 224, 224));
        panelData_add.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelData_add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nombre:");
        panelData_add.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 60, 20));

        jLabel6.setText("Descripción:");
        panelData_add.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        panelData_add.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 400, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtDescripcion);

        panelData_add.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 400, 140));

        panelCreate.add(panelData_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 550, 260));

        btnAdd.setBackground(new java.awt.Color(153, 153, 153));
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Guardar información");
        btnAdd.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        panelCreate.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 130, 30));

        panelDerecha1.add(panelCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 500));

        panelRead.setBackground(new java.awt.Color(255, 255, 255));
        panelRead.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Descripcion", "Cantidad"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(2).setMinWidth(200);
            tabla.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        panelRead.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 56, 626, 407));

        btnLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupita.png"))); // NOI18N
        btnLupa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRead.add(btnLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 40, 30));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRead.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 30));

        txtBuscador.setBorder(null);
        txtBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscadorMouseClicked(evt);
            }
        });
        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyTyped(evt);
            }
        });
        panelRead.add(txtBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 520, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        panelRead.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 520, 20));

        panelDerecha1.add(panelRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 500));

        panelUpdate.setBackground(new java.awt.Color(255, 255, 255));
        panelUpdate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel12.setText("Modificar proveedores:");
        panelUpdate.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        panelUpdate.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 130, 10));

        btnAdd1.setBackground(new java.awt.Color(153, 153, 153));
        btnAdd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd1MouseClicked(evt);
            }
        });
        btnAdd1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Guardar información");
        btnAdd1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        panelUpdate.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 130, 30));

        panelData_edit.setBackground(new java.awt.Color(224, 224, 224));
        panelData_edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelData_edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Nombre:");
        panelData_edit.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 50, 20));

        jLabel15.setText("Descripcion:");
        panelData_edit.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        panelData_edit.add(boxCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 100, -1));

        txtNombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre1KeyTyped(evt);
            }
        });
        panelData_edit.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 420, -1));

        jLabel20.setText("Código de producto:");
        panelData_edit.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtBuscador1.setBorder(null);
        txtBuscador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscador1MouseClicked(evt);
            }
        });
        txtBuscador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscador1KeyTyped(evt);
            }
        });
        panelData_edit.add(txtBuscador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 160, 20));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        panelData_edit.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 160, 20));

        btnActualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btnActualizar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelData_edit.add(btnActualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 40, 40));

        btnLupa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupita.png"))); // NOI18N
        btnLupa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelData_edit.add(btnLupa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 40, 40));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        panelData_edit.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 550, 10));

        txtDescripcion1.setColumns(20);
        txtDescripcion1.setRows(5);
        txtDescripcion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcion1KeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(txtDescripcion1);

        panelData_edit.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 420, 110));

        panelUpdate.add(panelData_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 550, 260));

        panelDerecha1.add(panelUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 500));

        panelDelete.setBackground(new java.awt.Color(255, 255, 255));
        panelDelete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel21.setText("Eliminar productos:");
        panelDelete.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        panelDelete.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 110, 10));

        btnAdd2.setBackground(new java.awt.Color(153, 153, 153));
        btnAdd2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd2MouseClicked(evt);
            }
        });
        btnAdd2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Eliminar producto");
        btnAdd2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        panelDelete.add(btnAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 130, 30));

        panelData_edit1.setBackground(new java.awt.Color(224, 224, 224));
        panelData_edit1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelData_edit1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setText("Nombre:");
        panelData_edit1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 50, 20));

        jLabel24.setText("Descripcion:");
        panelData_edit1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        panelData_edit1.add(boxCod2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 100, -1));

        txtNombre2.setEditable(false);
        txtNombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre2KeyTyped(evt);
            }
        });
        panelData_edit1.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 420, -1));

        jLabel29.setText("Código de producto:");
        panelData_edit1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtBuscador2.setBorder(null);
        txtBuscador2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscador2MouseClicked(evt);
            }
        });
        txtBuscador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscador2KeyTyped(evt);
            }
        });
        panelData_edit1.add(txtBuscador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 160, 20));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        panelData_edit1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 160, 20));

        btnActualizar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btnActualizar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelData_edit1.add(btnActualizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 40, 40));

        btnLupa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupita.png"))); // NOI18N
        btnLupa2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelData_edit1.add(btnLupa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 40, 40));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        panelData_edit1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 550, 10));

        txtDescripcion2.setEditable(false);
        txtDescripcion2.setColumns(20);
        txtDescripcion2.setRows(5);
        txtDescripcion2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcion2KeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(txtDescripcion2);

        panelData_edit1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 420, 110));

        panelDelete.add(panelData_edit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 550, 260));

        panelDerecha1.add(panelDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 500));

        panelDatos.add(panelDerecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 760, 500));

        panelDerecha2.setBackground(new java.awt.Color(255, 255, 255));
        panelDerecha2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCreate1.setBackground(new java.awt.Color(255, 255, 255));
        panelCreate1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Actualizar stock:");
        panelCreate1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        panelCreate1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 110, 10));

        panelData_add1.setBackground(new java.awt.Color(224, 224, 224));
        panelData_add1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelData_add1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Producto:");
        panelData_add1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 70, 20));

        jLabel9.setText("Proveedor:");
        panelData_add1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 90, -1));

        jLabel10.setText("Fecha de vencimiento:");
        panelData_add1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 90, 130, -1));

        panelData_add1.add(txtDist10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 160, -1));

        panelData_add1.add(txtCodprod10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 160, -1));
        panelData_add1.add(txtFecvenc10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 120, -1));

        jLabel5.setText("Cantidad:");
        panelData_add1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 70, -1));

        txtCantidad10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidad10KeyTyped(evt);
            }
        });
        panelData_add1.add(txtCantidad10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 160, -1));

        panelCreate1.add(panelData_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 550, 260));

        btnAdd10.setBackground(new java.awt.Color(153, 153, 153));
        btnAdd10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd10MouseClicked(evt);
            }
        });
        btnAdd10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Guardar información");
        btnAdd10.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        panelCreate1.add(btnAdd10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 130, 30));

        panelDerecha2.add(panelCreate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 500));

        panelRead1.setBackground(new java.awt.Color(255, 255, 255));
        panelRead1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Producto", "Fecha de vencimiento", "Proveedor", "Cantidad"
            }
        ));
        tabla11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla11MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tabla11);
        if (tabla11.getColumnModel().getColumnCount() > 0) {
            tabla11.getColumnModel().getColumn(2).setMinWidth(200);
            tabla11.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        panelRead1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 56, 626, 407));

        btnLupa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupita.png"))); // NOI18N
        btnLupa11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRead1.add(btnLupa11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 40, 30));

        btnActualizar11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btnActualizar11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRead1.add(btnActualizar11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 30));

        txtBuscador11.setBorder(null);
        txtBuscador11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscador11MouseClicked(evt);
            }
        });
        txtBuscador11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscador11KeyTyped(evt);
            }
        });
        panelRead1.add(txtBuscador11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 520, 20));

        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));
        panelRead1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 520, 20));

        panelDerecha2.add(panelRead1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 500));

        panelUpdate1.setBackground(new java.awt.Color(255, 255, 255));
        panelUpdate1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel17.setText("Modificar stock:");
        panelUpdate1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        panelUpdate1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, 10));

        btnAdd12.setBackground(new java.awt.Color(153, 153, 153));
        btnAdd12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd12MouseClicked(evt);
            }
        });
        btnAdd12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Guardar información");
        btnAdd12.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        panelUpdate1.add(btnAdd12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 130, 30));

        panelData_edit2.setBackground(new java.awt.Color(224, 224, 224));
        panelData_edit2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelData_edit2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Producto:");
        panelData_edit2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 60, 20));

        jLabel26.setText("Fecha de vencimiento:");
        panelData_edit2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 130, 130, -1));

        jLabel27.setText("Proveedor:");
        panelData_edit2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 60, -1));

        panelData_edit2.add(boxCod12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, -1));

        jLabel28.setText("Código de lista:");
        panelData_edit2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtBuscador12.setBorder(null);
        txtBuscador12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscador12MouseClicked(evt);
            }
        });
        txtBuscador12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscador12KeyTyped(evt);
            }
        });
        panelData_edit2.add(txtBuscador12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 160, 20));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        panelData_edit2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 160, 20));

        btnActualizar12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btnActualizar12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelData_edit2.add(btnActualizar12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 40, 40));

        btnLupa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupita.png"))); // NOI18N
        btnLupa12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelData_edit2.add(btnLupa12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 40, 40));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        panelData_edit2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 550, 10));

        panelData_edit2.add(txtDist12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 180, -1));

        panelData_edit2.add(txtCodproducto12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 180, -1));
        panelData_edit2.add(txtFecvenc12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 130, -1));

        jLabel16.setText("Cantidad:");
        panelData_edit2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 60, -1));

        txtCantidad12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidad12KeyTyped(evt);
            }
        });
        panelData_edit2.add(txtCantidad12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 180, -1));

        panelUpdate1.add(panelData_edit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 550, 260));

        panelDerecha2.add(panelUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 500));

        panelDelete1.setBackground(new java.awt.Color(255, 255, 255));
        panelDelete1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel31.setText("Eliminar productos:");
        panelDelete1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        panelDelete1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 110, 10));

        btnAdd13.setBackground(new java.awt.Color(153, 153, 153));
        btnAdd13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd13MouseClicked(evt);
            }
        });
        btnAdd13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Eliminar producto");
        btnAdd13.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        panelDelete1.add(btnAdd13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 130, 30));

        panelData_edit3.setBackground(new java.awt.Color(224, 224, 224));
        panelData_edit3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelData_edit3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setText("Producto:");
        panelData_edit3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 60, 20));

        jLabel34.setText("Fecha de vencimiento:");
        panelData_edit3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 130, 130, -1));

        jLabel35.setText("Proveedor:");
        panelData_edit3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 170, 70, -1));

        panelData_edit3.add(boxCod13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, -1));

        jLabel36.setText("Código de lista:");
        panelData_edit3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtBuscador13.setBorder(null);
        txtBuscador13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscador13MouseClicked(evt);
            }
        });
        txtBuscador13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscador13KeyTyped(evt);
            }
        });
        panelData_edit3.add(txtBuscador13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 160, 20));

        jSeparator15.setForeground(new java.awt.Color(0, 0, 0));
        panelData_edit3.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 160, 20));

        btnActualizar13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btnActualizar13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelData_edit3.add(btnActualizar13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 40, 40));

        btnLupa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupita.png"))); // NOI18N
        btnLupa13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelData_edit3.add(btnLupa13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 40, 40));

        jSeparator16.setForeground(new java.awt.Color(0, 0, 0));
        panelData_edit3.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 550, 10));

        txtDist13.setEnabled(false);
        panelData_edit3.add(txtDist13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 170, -1));

        jLabel25.setText("Cantidad:");
        panelData_edit3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 60, -1));

        txtFecvenc13.setEnabled(false);
        panelData_edit3.add(txtFecvenc13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 120, -1));

        txtCodproducto13.setEnabled(false);
        panelData_edit3.add(txtCodproducto13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 170, -1));

        txtCantidad13.setEditable(false);
        panelData_edit3.add(txtCantidad13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 170, -1));

        panelDelete1.add(panelData_edit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 550, 260));

        panelDerecha2.add(panelDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 500));

        panelDatos.add(panelDerecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 760, 500));

        add(panelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void panelAnadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnadirMouseClicked
        if(opcion==1){
            cprod.visible_create();
            //SE CAMBIA EL TITULO
            txtTitulo.setText("AÑADIR PRODUCTOS");
            //SE LIMPIAN LOS COMPOS
            cprod.limpiar_campos();
        }else if(opcion==2){
            clist_prod.visible_create();
            //SE CAMBIA EL TITULO
            txtTitulo.setText("AÑADIR STOCK");
            //SE LIMPIAN LOS COMBOBOXES
            clist_prod.limpiar_combobox();
            //llenar comboboxes
            clist_prod.listar_combobox10();
            //SE LIMPIAN LOS COMPOS
            clist_prod.limpiar_campos();
        }
    }//GEN-LAST:event_panelAnadirMouseClicked

    private void panelAnadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnadirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAnadirMouseEntered

    private void panelAnadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnadirMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAnadirMouseExited

    private void panelListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelListarMouseClicked
        if(opcion==1){
            cprod.visible_read();
            //SE CAMBIA EL TITULO
            txtTitulo.setText("VISTA DE PRODUCTOS");
            //LISTA USUARIOS
            cprod.limpiar_campos();
            cprod.limpiarTabla();
            cprod.listar();
        }else if(opcion==2){
            clist_prod.visible_read();
            //SE CAMBIA EL TITULO
            txtTitulo.setText("VISTA DE LISTA DE PRODUCTOS");
            //LISTA USUARIOS
            clist_prod.limpiar_campos();
            clist_prod.limpiarTabla();
            clist_prod.listar();
        }
    }//GEN-LAST:event_panelListarMouseClicked

    private void panelListarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelListarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelListarMouseEntered

    private void panelListarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelListarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelListarMouseExited

    private void panelModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelModificarMouseClicked
        if(opcion==1){
            cprod.visible_update();
            //SE CAMBIA EL TITULO
            txtTitulo.setText("MODIFICAR PRODUCTOS");
            //SE LIMPIAN LOS COMBOBOXES
            cprod.limpiar_combobox();
            //llenar comboboxes
            cprod.listar_combobox1();
            //SE LIMPIAN LOS CAMPOS
            cprod.limpiar_campos();
            //SE BLOQUEAN LOS CAMPOS
            cprod.bloquear_camposUpdate();
        }else if(opcion==2){
            clist_prod.visible_update();
            //SE CAMBIA EL TITULO
            txtTitulo.setText("MODIFICAR STOCK");
            //SE LIMPIAN LOS COMBOBOXES
            clist_prod.limpiar_combobox();
            //llenar comboboxes
            clist_prod.listar_combobox12();
            //SE LIMPIAN LOS CAMPOS
            clist_prod.limpiar_campos();
            //SE BLOQUEAN LOS CAMPOS
            clist_prod.bloquear_camposUpdate();
        }
    }//GEN-LAST:event_panelModificarMouseClicked

    private void panelModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelModificarMouseEntered

    }//GEN-LAST:event_panelModificarMouseEntered

    private void panelModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelModificarMouseExited

    }//GEN-LAST:event_panelModificarMouseExited

    private void panelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEliminarMouseClicked
        if(opcion==1){
            cprod.visible_delete();
            //SE CAMBIA EL TITULO
            txtTitulo.setText("ELIMINAR PRODUCTOS");
            //SE LIMPIAN LOS COMBOBOXES
            cprod.limpiar_combobox();
            //llenar comboboxes
            cprod.listar_combobox2();
            //SE LIMPIAN LOS CAMPOS
            cprod.limpiar_campos();
        }else if(opcion==2){
            clist_prod.visible_delete();
            //SE CAMBIA EL TITULO
            txtTitulo.setText("ELIMINAR PRODUCTOS");
            //SE LIMPIAN LOS COMBOBOXES
            clist_prod.limpiar_combobox();
            //llenar comboboxes
            clist_prod.listar_combobox13();
            //SE LIMPIAN LOS CAMPOS
            clist_prod.limpiar_campos();
        }
    }//GEN-LAST:event_panelEliminarMouseClicked

    private void panelEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEliminarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEliminarMouseEntered

    private void panelEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEliminarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEliminarMouseExited

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked

    }//GEN-LAST:event_tablaMouseClicked

    private void txtBuscadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorMouseClicked
        if(this.txtBuscador.getText().equals("Ingrese nombre del Producto")){
            this.txtBuscador.setText("");
            this.txtBuscador.setForeground(Color.BLACK);
            this.txtBuscador.getCaret().setVisible(true);
        }
    }//GEN-LAST:event_txtBuscadorMouseClicked

    private void txtBuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtBuscadorKeyTyped

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        if(this.txtNombre.getText().equals("")||this.txtDescripcion.getText().equals("")||
            this.txtDescripcion.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }else{
            cprod.agregar();
            cprod.limpiarTabla();
            cprod.limpiar_campos();
            cprod.listar();
            //SE HACE VISIBLE EL READ
            cprod.visible_read();
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnAdd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd1MouseClicked
        if(this.txtNombre1.getText().equals("")||this.txtDescripcion1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }else{
            //SE EDITA
            cprod.actualizar();
            //SE LIMPIAN LOS DATOS
            cprod.limpiar_campos();
            //REDIRIGIR A READ
            cprod.visible_read();
            //limpiar
            cprod.limpiar_campos();
            cprod.limpiarTabla();
            //listar
            cprod.listar();
        }
    }//GEN-LAST:event_btnAdd1MouseClicked

    private void txtNombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre1KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtNombre1KeyTyped

    private void txtBuscador1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscador1MouseClicked
        if(this.txtBuscador1.getText().equals("Ingrese código del Producto")){
            this.txtBuscador1.setText("");
            this.txtBuscador1.setForeground(Color.BLACK);
            this.txtBuscador1.getCaret().setVisible(true);
        }
    }//GEN-LAST:event_txtBuscador1MouseClicked

    private void txtBuscador1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscador1KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
        if(this.txtBuscador1.getText().length()>=9){
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscador1KeyTyped

    private void btnAdd2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd2MouseClicked
        //SE ELIMINA
        boolean bandera_delete=cprod.eliminar();
        if(bandera_delete){
            //SE LIMPIAN LOS DATOS
            cprod.limpiar_campos();
            //REDIRIGIR A READ
            cprod.visible_read();
            //limpiar
            cprod.limpiar_campos();
            cprod.limpiarTabla();
            //listar
            cprod.listar();
        }
    }//GEN-LAST:event_btnAdd2MouseClicked

    private void txtNombre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre2KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtNombre2KeyTyped

    private void txtBuscador2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscador2MouseClicked
        if(this.txtBuscador2.getText().equals("Ingrese código del Producto")){
            this.txtBuscador2.setText("");
            this.txtBuscador2.setForeground(Color.BLACK);
            this.txtBuscador2.getCaret().setVisible(true);
        }
    }//GEN-LAST:event_txtBuscador2MouseClicked

    private void txtBuscador2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscador2KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
        if(this.txtBuscador2.getText().length()>=9){
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscador2KeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char validar = evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtDescripcionKeyTyped

    private void txtDescripcion1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcion1KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtDescripcion1KeyTyped

    private void txtDescripcion2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcion2KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtDescripcion2KeyTyped

    private void casilla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla1MouseClicked
        opcion=1;
        //APARECE LA X EN LA CASILLA 1
        metodo.TamanoDinamico("/img/imgSeleccion.png", selector1,this);
        
        //DESAPARECE LA X DE LA CASILLA 2
        this.selector2.setIcon(null);
        //SE CAMBIA EL ICON A PRODUCTO
        metodo.TamanoDinamico("/img/imgProducto.png", icon, this);
        //SE HACE VISIBLE EL PANEL DERECHA1
        this.panelDerecha1.setVisible(true);
        this.panelDerecha2.setVisible(false);
        
        this.panelCreate.setVisible(false);
        this.panelRead.setVisible(false);
        this.panelUpdate.setVisible(false);
        this.panelDelete.setVisible(false);
        
        this.txtTitulo.setText("GESTIONAR PRODUCTOS");
        
        this.repaint();
    }//GEN-LAST:event_casilla1MouseClicked

    private void casilla2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla2MouseClicked
        opcion=2;
        //APARECE LA X EN LA CASILLA 2
        metodo.TamanoDinamico("/img/imgSeleccion.png", selector2,this);
        
        //DESAPARECE LA X DE LA CASILLA 1
        this.selector1.setIcon(null);
        
        //SE CAMBIA EL ICON A PRODUCTO
        metodo.TamanoDinamico("/img/imgActualizarStock.png", icon, this);
        //SE HACE VISIBLE EL PANEL DERECHA2
        this.panelDerecha2.setVisible(true);
        this.panelDerecha1.setVisible(false);
        
        this.panelCreate1.setVisible(false);
        this.panelRead1.setVisible(false);
        this.panelUpdate1.setVisible(false);
        this.panelDelete1.setVisible(false);
        
        this.txtTitulo.setText("GESTIONAR STOCK");
        
        this.repaint();
    }//GEN-LAST:event_casilla2MouseClicked

    private void btnAdd12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd12MouseClicked
        if(this.txtCodproducto12.getSelectedIndex()==-1||this.txtFecvenc12.getDate().toString().equals("")||
                this.txtDist12.getSelectedIndex()==-1||this.txtCantidad12.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }else{
            //SE EDITA
            clist_prod.actualizar();
            //SE LIMPIAN LOS DATOS
            clist_prod.limpiar_campos();
            //REDIRIGIR A READ
            clist_prod.visible_read();
            //limpiar
            clist_prod.limpiar_campos();
            clist_prod.limpiarTabla();
            //listar
            clist_prod.listar();
        }
    }//GEN-LAST:event_btnAdd12MouseClicked

    private void txtBuscador12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscador12MouseClicked
        if(this.txtBuscador12.getText().equals("Ingrese código del Producto")){
            this.txtBuscador12.setText("");
            this.txtBuscador12.setForeground(Color.BLACK);
            this.txtBuscador12.getCaret().setVisible(true);
        }
    }//GEN-LAST:event_txtBuscador12MouseClicked

    private void txtBuscador12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscador12KeyTyped
       char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
        if(this.txtBuscador12.getText().length()>=9){
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscador12KeyTyped

    private void btnAdd10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd10MouseClicked
        if(this.txtCodprod10.getSelectedIndex()==-1||this.txtFecvenc10.getDate().toString().equals("")||
                this.txtDist10.getSelectedIndex()==-1||this.txtCantidad10.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }else{
            clist_prod.agregar();
            clist_prod.limpiarTabla();
            clist_prod.limpiar_campos();
            clist_prod.listar();
            //SE HACE VISIBLE EL READ
            clist_prod.visible_read();
        }
    }//GEN-LAST:event_btnAdd10MouseClicked

    private void btnAdd13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd13MouseClicked
        //SE ELIMINA
        boolean bandera_delete=clist_prod.eliminar();
        if(bandera_delete){
            //SE LIMPIAN LOS DATOS
            clist_prod.limpiar_campos();
            //REDIRIGIR A READ
            clist_prod.visible_read();
            //limpiar
            clist_prod.limpiar_campos();
            clist_prod.limpiarTabla();
            //listar
            clist_prod.listar();
        }
    }//GEN-LAST:event_btnAdd13MouseClicked

    private void txtBuscador13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscador13MouseClicked
        if(this.txtBuscador13.getText().equals("Ingrese código del Producto")){
            this.txtBuscador13.setText("");
            this.txtBuscador13.setForeground(Color.BLACK);
            this.txtBuscador13.getCaret().setVisible(true);
        }
    }//GEN-LAST:event_txtBuscador13MouseClicked

    private void txtBuscador13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscador13KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
        if(this.txtBuscador13.getText().length()>=9){
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscador13KeyTyped

    private void tabla11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla11MouseClicked

    private void txtBuscador11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscador11MouseClicked
        if(this.txtBuscador11.getText().equals("Ingrese nombre del Producto")){
            this.txtBuscador11.setText("");
            this.txtBuscador11.setForeground(Color.BLACK);
            this.txtBuscador11.getCaret().setVisible(true);
        }
    }//GEN-LAST:event_txtBuscador11MouseClicked

    private void txtBuscador11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscador11KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtBuscador11KeyTyped

    private void txtCantidad10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad10KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_txtCantidad10KeyTyped

    private void txtCantidad12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad12KeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_txtCantidad12KeyTyped
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boxCod;
    public javax.swing.JComboBox<String> boxCod12;
    public javax.swing.JComboBox<String> boxCod13;
    public javax.swing.JComboBox<String> boxCod2;
    public javax.swing.JLabel btnActualizar;
    public javax.swing.JLabel btnActualizar1;
    public javax.swing.JLabel btnActualizar11;
    public javax.swing.JLabel btnActualizar12;
    public javax.swing.JLabel btnActualizar13;
    public javax.swing.JLabel btnActualizar2;
    private javax.swing.JPanel btnAdd;
    private javax.swing.JPanel btnAdd1;
    private javax.swing.JPanel btnAdd10;
    private javax.swing.JPanel btnAdd12;
    private javax.swing.JPanel btnAdd13;
    private javax.swing.JPanel btnAdd2;
    public javax.swing.JLabel btnLupa;
    public javax.swing.JLabel btnLupa1;
    public javax.swing.JLabel btnLupa11;
    public javax.swing.JLabel btnLupa12;
    public javax.swing.JLabel btnLupa13;
    public javax.swing.JLabel btnLupa2;
    private javax.swing.JLabel casilla1;
    private javax.swing.JLabel casilla2;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JPanel panelAnadir;
    public javax.swing.JPanel panelCreate;
    public javax.swing.JPanel panelCreate1;
    private javax.swing.JPanel panelData_add;
    private javax.swing.JPanel panelData_add1;
    private javax.swing.JPanel panelData_edit;
    private javax.swing.JPanel panelData_edit1;
    private javax.swing.JPanel panelData_edit2;
    private javax.swing.JPanel panelData_edit3;
    public javax.swing.JPanel panelDatos;
    public javax.swing.JPanel panelDelete;
    public javax.swing.JPanel panelDelete1;
    private javax.swing.JPanel panelDerecha1;
    private javax.swing.JPanel panelDerecha2;
    public javax.swing.JPanel panelEliminar;
    private javax.swing.JPanel panelIzquierda;
    public javax.swing.JPanel panelListar;
    public javax.swing.JPanel panelModificar;
    public javax.swing.JPanel panelRead;
    public javax.swing.JPanel panelRead1;
    private javax.swing.JPanel panelSuperior;
    public javax.swing.JPanel panelUpdate;
    public javax.swing.JPanel panelUpdate1;
    private javax.swing.JLabel selector1;
    private javax.swing.JLabel selector2;
    public javax.swing.JTable tabla;
    public javax.swing.JTable tabla11;
    private javax.swing.JLabel txtAnadir;
    private javax.swing.JLabel txtAnadir1;
    public javax.swing.JTextField txtBuscador;
    public javax.swing.JTextField txtBuscador1;
    public javax.swing.JTextField txtBuscador11;
    public javax.swing.JTextField txtBuscador12;
    public javax.swing.JTextField txtBuscador13;
    public javax.swing.JTextField txtBuscador2;
    public javax.swing.JTextField txtCantidad10;
    public javax.swing.JTextField txtCantidad12;
    public javax.swing.JTextField txtCantidad13;
    public javax.swing.JComboBox<String> txtCodprod10;
    public javax.swing.JComboBox<String> txtCodproducto12;
    public javax.swing.JComboBox<String> txtCodproducto13;
    public javax.swing.JTextArea txtDescripcion;
    public javax.swing.JTextArea txtDescripcion1;
    public javax.swing.JTextArea txtDescripcion2;
    public javax.swing.JComboBox<String> txtDist10;
    public javax.swing.JComboBox<String> txtDist12;
    public javax.swing.JComboBox<String> txtDist13;
    private javax.swing.JLabel txtEliminar;
    public com.toedter.calendar.JDateChooser txtFecvenc10;
    public com.toedter.calendar.JDateChooser txtFecvenc12;
    public com.toedter.calendar.JDateChooser txtFecvenc13;
    private javax.swing.JLabel txtModificar;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNombre1;
    public javax.swing.JTextField txtNombre2;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
