/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Controller.ControllerPedido;
import Controller.ControllerRealizarPago;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author arnol
 */
public class RealizarPago extends javax.swing.JFrame {
    int xMouse, yMouse;
    public ControllerRealizarPago crp=new ControllerRealizarPago(this);
    /**
     * Creates new form Pagar
     */
    public RealizarPago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        panelSalir = new javax.swing.JPanel();
        textSalir = new javax.swing.JLabel();
        panelMini = new javax.swing.JPanel();
        textMini = new javax.swing.JLabel();
        panelNombre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelEfectivo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        boxPagocompleto = new javax.swing.JComboBox<>();
        txtMontodado = new javax.swing.JTextField();
        txtVuelto = new javax.swing.JTextField();
        panelDatopago = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        boxTipoPago = new javax.swing.JComboBox<>();
        txtTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        boxCod = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnPagar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSuperior.setBackground(new java.awt.Color(255, 255, 255));
        panelSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelSuperiorMouseDragged(evt);
            }
        });
        panelSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelSuperiorMousePressed(evt);
            }
        });

        panelSalir.setBackground(new java.awt.Color(255, 255, 255));

        textSalir.setFont(new java.awt.Font("Dialog", 0, 26)); // NOI18N
        textSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textSalir.setText("X");
        textSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSalirLayout = new javax.swing.GroupLayout(panelSalir);
        panelSalir.setLayout(panelSalirLayout);
        panelSalirLayout.setHorizontalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(textSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelSalirLayout.setVerticalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(textSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelMini.setBackground(new java.awt.Color(255, 255, 255));

        textMini.setBackground(new java.awt.Color(255, 255, 255));
        textMini.setFont(new java.awt.Font("Eras Medium ITC", 1, 30)); // NOI18N
        textMini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textMini.setText("--");
        textMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textMiniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textMiniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textMiniMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMiniLayout = new javax.swing.GroupLayout(panelMini);
        panelMini.setLayout(panelMiniLayout);
        panelMiniLayout.setHorizontalGroup(
            panelMiniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMiniLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(textMini, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMiniLayout.setVerticalGroup(
            panelMiniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMiniLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(textMini, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                .addContainerGap(354, Short.MAX_VALUE)
                .addComponent(panelMini, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(panelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(326, 326, 326))
        );

        jPanel1.add(panelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 50));

        panelNombre.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pago efectivo");

        javax.swing.GroupLayout panelNombreLayout = new javax.swing.GroupLayout(panelNombre);
        panelNombre.setLayout(panelNombreLayout);
        panelNombreLayout.setHorizontalGroup(
            panelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(panelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNombreLayout.setVerticalGroup(
            panelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
            .addGroup(panelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
        );

        jPanel1.add(panelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 90, 20));

        panelEfectivo.setBackground(new java.awt.Color(255, 255, 255));
        panelEfectivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelEfectivo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Pago completo:");
        panelEfectivo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setText("Monto dado:");
        panelEfectivo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        panelEfectivo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 180, 10));

        jLabel4.setText("Vuelto:");
        panelEfectivo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        boxPagocompleto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        boxPagocompleto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxPagocompletoItemStateChanged(evt);
            }
        });
        panelEfectivo.add(boxPagocompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 70, -1));

        txtMontodado.setEditable(false);
        txtMontodado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMontodadoMouseClicked(evt);
            }
        });
        txtMontodado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontodadoKeyTyped(evt);
            }
        });
        panelEfectivo.add(txtMontodado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 70, -1));

        txtVuelto.setEditable(false);
        panelEfectivo.add(txtVuelto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 70, -1));

        jPanel1.add(panelEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, 160));

        panelDatopago.setBackground(new java.awt.Color(255, 255, 255));
        panelDatopago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatopago.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Método de pago:");
        panelDatopago.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, -1));

        boxTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta", "Efectivo" }));
        boxTipoPago.setSelectedIndex(1);
        boxTipoPago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxTipoPagoItemStateChanged(evt);
            }
        });
        panelDatopago.add(boxTipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 80, -1));

        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalKeyTyped(evt);
            }
        });
        panelDatopago.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 80, -1));

        jLabel6.setText("Total:");
        panelDatopago.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        panelDatopago.add(boxCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 80, -1));

        jLabel8.setText("Cliente:");
        panelDatopago.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jPanel1.add(panelDatopago, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 200, 160));

        btnPagar.setBackground(new java.awt.Color(0, 0, 0));
        btnPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPagarMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pagar");

        javax.swing.GroupLayout btnPagarLayout = new javax.swing.GroupLayout(btnPagar);
        btnPagar.setLayout(btnPagarLayout);
        btnPagarLayout.setHorizontalGroup(
            btnPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        btnPagarLayout.setVerticalGroup(
            btnPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textSalirMouseClicked
        //this.setExtendedState(ICONIFIED);
        this.dispose();
        ControllerRealizarPago.pagar=false;
    }//GEN-LAST:event_textSalirMouseClicked

    private void textSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textSalirMouseEntered
        panelSalir.setBackground(Color.red);
        textSalir.setForeground(Color.white);
    }//GEN-LAST:event_textSalirMouseEntered

    private void textSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textSalirMouseExited
        panelSalir.setBackground(Color.white);
        textSalir.setForeground(Color.black);
    }//GEN-LAST:event_textSalirMouseExited

    private void textMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMiniMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_textMiniMouseClicked

    private void textMiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMiniMouseEntered
        panelMini.setBackground(new Color(235, 235, 235));
    }//GEN-LAST:event_textMiniMouseEntered

    private void textMiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMiniMouseExited
        panelMini.setBackground(Color.white);
    }//GEN-LAST:event_textMiniMouseExited

    private void panelSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSuperiorMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_panelSuperiorMouseDragged

    private void panelSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSuperiorMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelSuperiorMousePressed

    private void boxPagocompletoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxPagocompletoItemStateChanged
        if(boxPagocompleto.getSelectedItem().toString().equals("Si")){
            this.txtMontodado.setEditable(false);
            this.txtMontodado.setText("");
            this.txtVuelto.setText("");
        }else{
            this.txtMontodado.setEditable(true);
        }
    }//GEN-LAST:event_boxPagocompletoItemStateChanged

    private void boxTipoPagoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxTipoPagoItemStateChanged
        if(this.boxTipoPago.getSelectedItem().toString().equals("Tarjeta")){
            this.panelEfectivo.setVisible(false);
            this.panelNombre.setVisible(false);
        }else{
            this.panelEfectivo.setVisible(true);
            this.panelNombre.setVisible(true);
        }
    }//GEN-LAST:event_boxTipoPagoItemStateChanged

    private void btnPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarMouseClicked
            if(boxTipoPago.getSelectedItem().toString().equals("Efectivo")){
                if(!(boxCod.getSelectedItem()==null)||!txtTotal.getText().equals("")){
                    crp.pagar();
                    ControllerPedido.productos.clear();
                    crp.cped.limpiarTabla();
                    crp.cped.listar();
                    this.dispose();
                    ControllerRealizarPago.pagar=false;
                }else{
                   JOptionPane.showMessageDialog(null, "Llene todos los campos!!");
                }
            }else if(boxTipoPago.getSelectedItem().toString().equals("Tarjeta")){
                if((!(boxCod.getSelectedItem()==null)||!txtTotal.getText().equals("")||txtMontodado.getText().equals(""))){
                    crp.pagar();
                    ControllerPedido.productos.clear();
                    crp.cped.limpiarTabla();
                    crp.cped.listar();
                    this.dispose();
                    ControllerRealizarPago.pagar=false;
                }else{
                   JOptionPane.showMessageDialog(null, "Llene todos los campos!!");
                }
            }
        
        
    }//GEN-LAST:event_btnPagarMouseClicked

    private void txtTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_txtTotalKeyTyped

    private void txtMontodadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMontodadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontodadoMouseClicked

    private void txtMontodadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontodadoKeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_txtMontodadoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boxCod;
    public javax.swing.JComboBox<String> boxPagocompleto;
    public javax.swing.JComboBox<String> boxTipoPago;
    private javax.swing.JPanel btnPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelDatopago;
    private javax.swing.JPanel panelEfectivo;
    private javax.swing.JPanel panelMini;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JPanel panelSalir;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JLabel textMini;
    private javax.swing.JLabel textSalir;
    public javax.swing.JTextField txtMontodado;
    public javax.swing.JTextField txtTotal;
    public javax.swing.JTextField txtVuelto;
    // End of variables declaration//GEN-END:variables
}
